version: "3.9"

services:
    lacuna:
        build: .
        restart: unless-stopped
        environment:
            LACUNA_PUBSUB_PROJECT_ID: pubsub
            # Configure the pubsub client to use the emulator
            # See https://cloud.google.com/pubsub/docs/emulator#env
            PUBSUB_EMULATOR_HOST: pubsub:8085
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    json-server:
        image: codfish/json-server:latest
        restart: unless-stopped
        ports:
            - "8080:80"
        labels:
            lacuna.enabled: true
            lacuna.subscription.test.topic: test
            lacuna.subscription.test.endpoint: http://json-server/messages
            lacuna.subscription.test.ack-deadline: "30s"
    pubsub:
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
        command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=pubsub
        restart: unless-stopped
        ports:
            - "8085:8085"
